config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  unless SolidusContent.config.skip_default_route
    get '/c/:type(/:id)', to: 'solidus_content#show', id: :default, as: :solidus_content
  end

  namespace :admin do
    scope path: "content" do
      resources :entry_types, path: "types"
      resources :entries
    end
  end
end

app/models/solidus_content/application_record.rb
# frozen_string_literal: true

class SolidusContent::ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/solidus_content/entry.rb
# frozen_string_literal: true

class SolidusContent::Entry < SolidusContent::ApplicationRecord
  include SolidusContent::Provider::Fields

  belongs_to :entry_type

  after_initialize { self.options ||= {} }
  after_initialize :inject_entry_fields, if: :entry_type_id?

  validates :slug, presence: true, uniqueness: { scope: :entry_type_id }

  scope :by_slug, ->(slug) { find_by!(slug: slug) }
  scope :by_type, ->(type) {
    unless type.is_a? SolidusContent::EntryType
      type = SolidusContent::EntryType.by_name(type)
    end
    where(entry_type: type)
  }

  def self.data_for(type, slug)
    by_type(type).by_slug(slug).data
  end

  def data
    content[:data]
  end

  def content
    @content ||= entry_type.content_for(self)
  end

  def entry_fields
    return unless entry_type_id?

    entry_type.provider_class.entry_fields
  end

  private

  def inject_entry_fields
    provider_based_attr_reader(entry_fields)
  end
end

app/models/solidus_content/entry_type.rb
# frozen_string_literal: true

class SolidusContent::EntryType < SolidusContent::ApplicationRecord
  include SolidusContent::Provider::Fields

  has_many :entries, dependent: :destroy

  scope :by_name, ->(name) { find_by!(name: name) }

  validates :name, presence: true
  validates :provider_name, presence: true
  validates :name, :provider_name, presence: true
  validate :ensure_provider_name_is_not_changed

  after_initialize { self.options ||= {} }
  after_initialize :inject_provider_fields, if: :provider_name?

  scope :by_name, ->(name) { find_by!(name: name) }

  def content_for(entry)
    provider_class.call(
      slug: entry.slug,
      type: name,
      provider: provider_name,
      options: entry.options.symbolize_keys,
      type_options: options.symbolize_keys,
    )
  end

  def provider_class
    SolidusContent.config.providers[provider_name.to_sym]
  end

  def provider_name_readonly?
    persisted?
  end

  def entry_type_fields
    return unless provider_name

    provider_class.entry_type_fields
  end

  private

  def inject_provider_fields
    provider_based_attr_reader(entry_type_fields)
  end

  def ensure_provider_name_is_not_changed
    return unless provider_name_changed? && persisted?

    errors.add :provider_name, :readonly
  end
end

app/models/solidus_content/provider/fields.rb
# frozen_string_literal: true

module SolidusContent
  module Provider
    module Fields
      def provider_based_attr_reader(attrs)
        attrs.each do |attr|
          define_singleton_method(attr) do
            options[attr.to_s] || ''
          end

          define_singleton_method("#{attr}=") do |value|
            attribute_will_change!(:options)
            options[attr.to_s] = value
          end
        end
      end
    end
  end
end

app/controllers/solidus_content/resource_controller.rb
# frozen_string_literal: true

module SolidusContent
  class ResourceController < Spree::Admin::ResourceController
    private

    def location_after_save
      edit_object_url(@object)
    end

    def collection
      super.page(params[:page] || 0)
    end

    def model_class
      "SolidusContent::#{controller_name.classify}".constantize
    end

    def new_object_url(options = {})
      send(:"new_admin_#{controller_name.singularize}_path", options)
    end

    def edit_object_url(object, options = {})
      send(:"edit_admin_#{controller_name.singularize}_path", object, options)
    end

    def object_url(object = nil, options = {})
      send(:"admin_#{controller_name.singularize}_path", object, options)
    end

    def collection_url(options = {})
      send(:"admin_#{controller_name}_path", options)
    end
  end
end

app/controllers/spree/admin/entries_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class EntriesController < SolidusContent::ResourceController
      helper_method :model_class

      def show
        redirect_to action: :edit
      end

      private

      def permitted_resource_params
        params
          .require(:solidus_content_entry)
          .permit(:slug, :entry_type_id, *provider_params)
      end

      def provider_params
        @object.entry_fields || []
      end
    end
  end
end

app/controllers/spree/admin/entry_types_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class EntryTypesController < SolidusContent::ResourceController
      helper_method :model_class

      def show
        redirect_to action: :edit
      end

      private

      def permitted_resource_params
        params
          .require(:solidus_content_entry_type)
          .permit(:name, :provider_name, *provider_params)
      end

      def provider_params
        @object.entry_type_fields || []
      end
    end
  end
end

app/controllers/spree/solidus_content_controller.rb
# frozen_string_literal: true

require_dependency 'solidus_content/entry_type'

class Spree::SolidusContentController < Spree::StoreController
  def show
    slug = params[:id] || :default
    type = params[:type]

    @entry = ::SolidusContent::Entry.by_type(type).by_slug(slug)
    render action: type
  end
end

app/views/spree/admin/entries/_form.html.erb
<% entry_type_options = SolidusContent::EntryType.pluck(:name, :id) %>

<div data-hook="admin_entry_form_fields">
  <div class="row">
    <div class="left col-12" data-hook="admin_entry_form">
      <div class="row">
        <div class="col-6" data-hook="admin_entry_form_name">
          <%= form.field_container :slug do %>
            <%= form.field_hint :slug %>
            <%= form.label :slug, class: 'required' %><br />
            <%= form.text_field :slug, class: 'fullwidth' %>
          <% end %>
        </div>

        <div class="col-6" data-hook="admin_entry_form_provider">
          <%= form.field_container :entry_type_id do %>
            <%= form.field_hint :entry_type_id %>
            <%= form.label :entry_type_id, class: 'required' %><br />
            <%= form.select :entry_type_id, entry_type_options, { include_blank: false }, { disabled: form.object.persisted?, class: 'custom-select fullwidth' } %>
          <% end %>
        </div>

        <%= form.hidden_field :options, value: '{}' %>
      </div>
    </div>
  </div>

  <% if form.object.persisted? && @object.entry_fields.count > 0 %>
    <%= render "options_form", form: form %>
  <% end %>
</div>

app/views/spree/admin/entries/_options_form.html.erb
<fieldset class="no-border-bottom">
  <legend>
    <%= @entry.entry_type.name %>
    <%= model_class.human_attribute_name(:options) %>
    (<%= SolidusContent.human_provider_name(@entry.entry_type.provider_name) %>)
  </legend>

  <div class="row">
    <% @entry.entry_fields.each do |field| %>
      <div class="col-12" data-hook="admin_entry_<%= field %>">
        <div class="field" id="solidus_content_entry_<%= field %>_field">
          <%= form.label field %>
          <%= form.text_field field, class: 'fullwidth' %>
        </div>
      </div>
    <% end %>
  </div>
</fieldset>

app/views/spree/admin/entries/edit.html.erb
<% admin_breadcrumb link_to(plural_resource_name(model_class), spree.admin_entries_path) %>
<% admin_breadcrumb @object.slug %>

<%= render 'spree/shared/error_messages', target: @object %>

<%= form_for @entry, url: spree.admin_entry_path(@entry) do |form| %>
  <fieldset data-hook="edit_entry">
    <%= content_tag :legend, model_class.model_name.human %>
    <%= render 'form', form: form %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= submit_tag t('spree.actions.update'), class: 'btn btn-primary' %>
      <%= link_to t('spree.actions.cancel'), collection_url, class: 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/entries/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb plural_resource_name(model_class) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.admin.entry.new'), new_object_url, class: 'btn btn-primary' %>
  </li>
<% end if can?(:create, model_class) %>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_entries">
    <colgroup>
      <col style="width: 40%;">
      <col style="width: 40%;">
      <col style="width: 20%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= model_class.human_attribute_name(:slug) %></th>
        <th><%= model_class.human_attribute_name(:entry_type) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |entry| %>
        <tr id="<%= spree_dom_id entry %>" data-hook="admin_entries_index_rows">
          <td>
            <%= link_to entry.slug, object_url(entry) %>
          </td>
          <td>
            <%= link_to entry.entry_type.name, admin_entry_type_path(entry.entry_type) %>
          </td>
          <td class="actions" data-hook="admin_entries_index_row_actions">
            <%= link_to_edit entry, url: edit_object_url(entry),
              class: 'edit edit-entry' if can?(:update, entry) %>
            <%= link_to_delete entry, url: object_url(entry),
              class: 'trash delete-entry' if can?(:destroy, entry) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
      resource: model_class,
      new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/entries/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(model_class), collection_url) %>
<% admin_breadcrumb "#{t('spree.actions.new')} #{model_class.model_name.human}" %>


<%= render 'spree/shared/error_messages', target: @object %>

<%= form_for @object, url: collection_url do |form| %>
  <fieldset data-hook="new_entry">
    <legend align="center">
      <%= admin_hint nil, t('solidus_content.hints.new_entry') %>
      <%= t('new', scope: %w[spree admin entry]) %>
    </legend>

    <%= render 'form', form: form %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= submit_tag t('spree.actions.create'), class: 'btn btn-primary' %>
      <%= link_to t('spree.actions.cancel'), collection_url, class: 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/entry_types/_form.html.erb
<% provider_options = SolidusContent.provider_names.map do |name|
  [SolidusContent.human_provider_name(name), name]
end %>

<div data-hook="admin_entry_type_form_fields">
  <div class="row">
    <div class="left col-12" data-hook="admin_entry_type_form">
      <div class="row">
        <div class="col-6" data-hook="admin_entry_type_form_name">
          <%= form.field_container :user do %>
            <%= form.label :name, class: 'required' %><br />
            <%= form.text_field :name, class: 'fullwidth' %>
          <% end %>
        </div>

        <div class="col-6" data-hook="admin_entry_type_form_provider">
          <%= form.field_container :provider_name do %>
            <%= form.field_hint :provider_name %>
            <%= form.label :provider_name, class: 'required' %><br />
            <%= form.select :provider_name, provider_options, { include_blank: false }, { disabled: form.object.provider_name_readonly?, class: 'custom-select fullwidth' } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if form.object.provider_name_readonly? && @object.entry_type_fields.count > 0 %>
    <%= render "options_form", form: form %>
  <% end %>
</div>

app/views/spree/admin/entry_types/_options_form.html.erb
<fieldset class="options-form no-border-bottom">
  <legend>
    <%= SolidusContent.human_provider_name(@entry_type.provider_name) %>
    <%= model_class.human_attribute_name(:options) %>
  </legend>
  <div class="row">
    <% @entry_type.entry_type_fields.each do |field| %>
      <div class="col-12" data-hook="admin_entry_type_<%= field %>">
        <div class="field" id="solidus_content_entry_type_<%= field %>_field">
          <%= form.label field %>
          <%= form.text_field field, class: 'fullwidth' %>
        </div>
      </div>
    <% end %>
  </div>
</fieldset>

app/views/spree/admin/entry_types/edit.html.erb
<% admin_breadcrumb link_to(plural_resource_name(model_class), spree.admin_entry_types_path) %>
<% admin_breadcrumb @entry_type.name %>

<%= render 'spree/shared/error_messages', target: @object %>

<%= form_for @entry_type, url: spree.admin_entry_type_path(@entry_type) do |form| %>
  <fieldset data-hook="edit_entry_type">
    <%= content_tag :legend, model_class.model_name.human %>
    <%= render 'form', form: form %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= submit_tag t('spree.actions.update'), class: 'btn btn-primary' %>
      <%= link_to t('spree.actions.cancel'), collection_url, class: 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/entry_types/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb plural_resource_name(model_class) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.admin.entry_type.new'), new_object_url, class: 'btn btn-primary' %>
  </li>
<% end if can?(:create, model_class) %>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_entry_types">
    <colgroup>
      <col style="width: 40%;">
      <col style="width: 40%;">
      <col style="width: 20%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:provider) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |entry_type| %>
        <tr id="<%= spree_dom_id entry_type %>" data-hook="admin_entry_types_index_rows">
          <td>
            <%= link_to entry_type.name, object_url(entry_type) %>
          </td>
          <td>
            <%= entry_type.provider_name %>
          </td>
          <td class="actions" data-hook="admin_entry_types_index_row_actions">
            <%= link_to_edit entry_type, url: edit_object_url(entry_type),
              class: 'edit edit-entry-type' if can?(:update, entry_type) %>
            <%= link_to_delete entry_type, url: object_url(entry_type),
              class: 'trash delete-entry-type' if can?(:destroy, entry_type) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
      resource: model_class,
      new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/entry_types/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(model_class), collection_url) %>
<% admin_breadcrumb "#{t('spree.actions.new')} #{model_class.model_name.human}" %>


<%= render 'spree/shared/error_messages', target: @object %>

<%= form_for @object, url: collection_url do |form| %>
  <fieldset data-hook="new_entry_type">
    <legend align="center">
      <%= admin_hint nil, t('solidus_content.hints.new_entry_type') %>
      <%= t('new', scope: %w[spree admin entry_type]) %>
    </legend>

    <%= render 'form', form: form %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= submit_tag t('spree.actions.create'), class: 'btn btn-primary' %>
      <%= link_to t('spree.actions.cancel'), collection_url, class: 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/shared/_solidus_content_sub_menu.html.erb
<ul class="admin-subnav" data-hook="admin_settings_sub_tabs">
  <% if can?(:admin, SolidusContent::EntryType) %>
    <%= tab :entry_types, url: spree.admin_entry_types_path %>
  <% end %>

  <% if can?(:admin, SolidusContent::Entry) %>
    <%= tab :entries, url: spree.admin_entries_path %>
  <% end %>
</ul>